apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "glass.fullname" . }}-ntfy-cache
  labels:
    {{- include "glass.ntfy.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ntfy.cacheSize }}
