apiVersion: v1
kind: Service
metadata:
  name: {{ include "glass.fullname" . }}-ntfy
  labels:
    {{- include "glass.ntfy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ntfyPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "glass.ntfy.selectorLabels" . | nindent 4 }}
