apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "glass.fullname" . }}-peer-data
  labels:
    {{- include "glass.peer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.peer.dataSize }}
